"""create recipe first db

Revision ID: 7e365305a4a6
Revises: 
Create Date: 2019-07-28 05:12:24.643827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e365305a4a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('recipe_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('recipe_image', sa.String(length=128), nullable=True),
    sa.Column('recipe_name', sa.String(length=164), nullable=False),
    sa.Column('course', sa.String(length=164), nullable=False),
    sa.Column('food_category', sa.String(length=164), nullable=False),
    sa.Column('cuisine', sa.String(length=164), nullable=False),
    sa.Column('prep_time', sa.String(length=164), nullable=False),
    sa.Column('cook_time', sa.String(length=164), nullable=False),
    sa.Column('allergens', sa.String(length=164), nullable=False),
    sa.Column('serving', sa.String(length=164), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('recipe_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_post')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
